services:
  - type: web
    name: easy-gift-search-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
