services:
  - type: web
    name: easy-gift-search
    env: static
    buildCommand: echo "No build required for static site"
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
